// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api/api.proto

package api

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/golang/protobuf/ptypes/empty"
	authentication "github.com/quocbang/arrows/pkg/protobuf/authentication"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

func init() { proto.RegisterFile("api/api.proto", fileDescriptor_1b40cafcd4234784) }

var fileDescriptor_1b40cafcd4234784 = []byte{
	// 200 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4d, 0x2c, 0xc8, 0xd4,
	0x4f, 0x2c, 0xc8, 0xd4, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x4b, 0x2c, 0x2a, 0xca, 0x2f,
	0x2f, 0x96, 0x92, 0x49, 0xcf, 0xcf, 0x4f, 0xcf, 0x49, 0xd5, 0x07, 0xcb, 0xe6, 0xe5, 0xe5, 0x97,
	0x24, 0x96, 0x64, 0xe6, 0xe7, 0x15, 0x43, 0x54, 0x49, 0x49, 0x43, 0x65, 0xc1, 0xbc, 0xa4, 0xd2,
	0x34, 0xfd, 0xd4, 0xdc, 0x82, 0x92, 0x4a, 0xa8, 0xa4, 0x64, 0x62, 0x69, 0x49, 0x46, 0x6a, 0x5e,
	0x49, 0x66, 0x32, 0x58, 0x8f, 0x7e, 0x69, 0x71, 0x6a, 0x11, 0x44, 0xca, 0xc8, 0x9b, 0x8b, 0xd9,
	0x31, 0xc0, 0x53, 0xc8, 0x85, 0x8b, 0xd5, 0x27, 0x3f, 0x3d, 0x33, 0x4f, 0x48, 0x44, 0x0f, 0x62,
	0x9d, 0x1e, 0x98, 0x1b, 0x94, 0x5a, 0x58, 0x9a, 0x5a, 0x5c, 0x22, 0x25, 0x84, 0x26, 0x5a, 0x90,
	0x53, 0xa9, 0x24, 0xd8, 0x74, 0xf9, 0xc9, 0x64, 0x26, 0x6e, 0x25, 0x36, 0xfd, 0x1c, 0x90, 0xa0,
	0x15, 0xa3, 0x96, 0x93, 0x6e, 0x94, 0x76, 0x7a, 0x66, 0x49, 0x46, 0x69, 0x92, 0x5e, 0x72, 0x7e,
	0xae, 0x7e, 0x61, 0x69, 0x7e, 0x72, 0x52, 0x62, 0x5e, 0xba, 0x3e, 0x44, 0xaf, 0x7e, 0x41, 0x76,
	0x3a, 0xc2, 0x79, 0x89, 0x05, 0x99, 0x49, 0x6c, 0x60, 0x9e, 0x31, 0x20, 0x00, 0x00, 0xff, 0xff,
	0x08, 0xa0, 0xf8, 0x4d, 0xf1, 0x00, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// APIClient is the client API for API service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type APIClient interface {
	// Login to access user agant.
	//
	// Required:
	// - UserName
	// - Password
	Login(ctx context.Context, in *authentication.LoginRequest, opts ...grpc.CallOption) (*authentication.LoginReply, error)
}

type aPIClient struct {
	cc *grpc.ClientConn
}

func NewAPIClient(cc *grpc.ClientConn) APIClient {
	return &aPIClient{cc}
}

func (c *aPIClient) Login(ctx context.Context, in *authentication.LoginRequest, opts ...grpc.CallOption) (*authentication.LoginReply, error) {
	out := new(authentication.LoginReply)
	err := c.cc.Invoke(ctx, "/arrows.API/Login", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// APIServer is the server API for API service.
type APIServer interface {
	// Login to access user agant.
	//
	// Required:
	// - UserName
	// - Password
	Login(context.Context, *authentication.LoginRequest) (*authentication.LoginReply, error)
}

func RegisterAPIServer(s *grpc.Server, srv APIServer) {
	s.RegisterService(&_API_serviceDesc, srv)
}

func _API_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(authentication.LoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/arrows.API/Login",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServer).Login(ctx, req.(*authentication.LoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _API_serviceDesc = grpc.ServiceDesc{
	ServiceName: "arrows.API",
	HandlerType: (*APIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Login",
			Handler:    _API_Login_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/api.proto",
}
