// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api/UDP/udp.proto

package UDP

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/quocbang/arrows/pkg/protobuf/authentication"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

func init() { proto.RegisterFile("api/UDP/udp.proto", fileDescriptor_bd8a7c1067acd11a) }

var fileDescriptor_bd8a7c1067acd11a = []byte{
	// 128 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x4c, 0x2c, 0xc8, 0xd4,
	0x0f, 0x75, 0x09, 0xd0, 0x2f, 0x4d, 0x29, 0xd0, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x4b,
	0x2c, 0x2a, 0xca, 0x2f, 0x2f, 0x96, 0x92, 0x4c, 0x2c, 0x2d, 0xc9, 0x48, 0xcd, 0x2b, 0xc9, 0x4c,
	0x4e, 0x2c, 0xc9, 0xcc, 0xcf, 0xd3, 0x2f, 0x2d, 0x4e, 0x2d, 0x82, 0x28, 0x31, 0xe2, 0xe6, 0xe2,
	0x0c, 0x75, 0x09, 0x70, 0x04, 0xab, 0x73, 0x32, 0x8c, 0xd2, 0x4f, 0xcf, 0x2c, 0xc9, 0x28, 0x4d,
	0xd2, 0x4b, 0xce, 0xcf, 0xd5, 0x2f, 0x2c, 0xcd, 0x4f, 0x4e, 0x4a, 0xcc, 0x4b, 0xd7, 0x87, 0x98,
	0xa2, 0x5f, 0x90, 0x9d, 0xae, 0x0f, 0xd6, 0x94, 0x54, 0x9a, 0xa6, 0x0f, 0xb5, 0x2c, 0x89, 0x0d,
	0x2c, 0x62, 0x0c, 0x08, 0x00, 0x00, 0xff, 0xff, 0x57, 0x2b, 0x77, 0x36, 0x7e, 0x00, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// UDPArrowsClient is the client API for UDPArrows service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UDPArrowsClient interface {
}

type uDPArrowsClient struct {
	cc *grpc.ClientConn
}

func NewUDPArrowsClient(cc *grpc.ClientConn) UDPArrowsClient {
	return &uDPArrowsClient{cc}
}

// UDPArrowsServer is the server API for UDPArrows service.
type UDPArrowsServer interface {
}

func RegisterUDPArrowsServer(s *grpc.Server, srv UDPArrowsServer) {
	s.RegisterService(&_UDPArrows_serviceDesc, srv)
}

var _UDPArrows_serviceDesc = grpc.ServiceDesc{
	ServiceName: "arrows.UDPArrows",
	HandlerType: (*UDPArrowsServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams:     []grpc.StreamDesc{},
	Metadata:    "api/UDP/udp.proto",
}
